import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [display,setdisplay]=useState("");

  useEffect(()=>{
    creating_user();
    
  },[]);
  const creating_user=async()=>{
    await axios.post("/api/hello",{
      firstname:"testing",
      lastname:"testing",
      username:"testinging",
      password:"testing"
    }).then(function(respose){
      setdisplay(respose.data);
    }).catch(function(err){
      console.log(err);
    });

    
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
           {display}
           
      </main>
    </>
  )
}
